---
name: shellcheck
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions: {}
jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
